name: Run Postman Collection


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - Dev


jobs:
  run-postman-tests:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.JOY_ASSURDLY }}


      - name: Run Postman collection
        run: |
          postman collection run "Assurdly_QA_T_est.postman_collection.json"
